version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "@camera.ui/rpc"
      - dependency-name: "@camera.ui/transport"
      - dependency-name: "@camera.ui/sdk"