export { CAMERA_UI_INJECTION_KEY, createCameraUiPlugin } from './plugin.js';
export type { CameraUiPlugin, CameraUiPluginInput } from './plugin.js';

export {
  acquireSensorManager,
  clearCameraCache,
  clearOAuthCache,
  clearPluginCache,
  clearSensorCache,
  clearSnapshotCache,
  clearStorageCache,
  createReactiveCameraDevice,
  createSensorManager,
  getSnapshotUrl,
  isReactiveAudioSensor,
  isReactiveBatteryInfo,
  isReactiveCarbonDioxideInfo,
  isReactiveCarbonMonoxideSensor,
  isReactiveClassifierSensor,
  isReactiveColdSensor,
  isReactiveContactSensor,
  isReactiveDoorbellTrigger,
  isReactiveFaceSensor,
  isReactiveGarageControl,
  isReactiveGasSensor,
  isReactiveHeatSensor,
  isReactiveHumidityInfo,
  isReactiveIlluminanceInfo,
  isReactiveLeakSensor,
  isReactiveLicensePlateSensor,
  isReactiveLightControl,
  isReactiveLockControl,
  isReactiveMotionSensor,
  isReactiveObjectSensor,
  isReactiveOccupancySensor,
  isReactivePowerSensor,
  isReactiveProblemSensor,
  isReactivePTZControl,
  isReactiveSecuritySystem,
  isReactiveSirenControl,
  isReactiveSmokeSensor,
  isReactiveSwitchControl,
  isReactiveTamperSensor,
  isReactiveTemperatureInfo,
  isReactiveVibrationSensor,
  refreshClientSubscriptions,
  releaseSensorManager,
  resetClientState,
  rpcCall,
  setFullscreenRoot,
  useAllSensors,
  useAudioSensor,
  useCameraById,
  useCameraStorage,
  useCameraStream,
  useCameraUi,
  useClassifierSensors,
  useCoreManager,
  useCuiFullscreen,
  useDeviceManager,
  useFaceSensor,
  useLicensePlateSensor,
  useMotionSensor,
  useOAuth,
  useObjectSensor,
  usePlugin,
  usePluginStorage,
  usePTZControl,
  useRpcCall,
  useRpcSubscription,
  useSensorById,
  useSensorByType,
  useSensors,
  useSensorsByType,
  useSensorStorage,
  useSnapshot,
  useTabVisibility,
  useTerminal,
  useTopmostFullscreenElement,
} from './composables/index.js';

export type {
  CameraStream,
  ReactiveAudioSensor,
  ReactiveBatteryInfo,
  ReactiveCarbonDioxideInfo,
  ReactiveCarbonMonoxideSensor,
  ReactiveClassifierSensor,
  ReactiveColdSensor,
  ReactiveContactSensor,
  ReactiveDoorbellTrigger,
  ReactiveFaceSensor,
  ReactiveGarageControl,
  ReactiveGasSensor,
  ReactiveHeatSensor,
  ReactiveHumidityInfo,
  ReactiveIlluminanceInfo,
  ReactiveLeakSensor,
  ReactiveLicensePlateSensor,
  ReactiveLightControl,
  ReactiveLockControl,
  ReactiveMotionSensor,
  ReactiveObjectSensor,
  ReactiveOccupancySensor,
  ReactivePowerSensor,
  ReactiveProblemSensor,
  ReactivePTZControl,
  ReactiveSecuritySystem,
  ReactiveSensor,
  ReactiveSensorManager,
  ReactiveSirenControl,
  ReactiveSmokeSensor,
  ReactiveStorage,
  ReactiveSwitchControl,
  ReactiveTamperSensor,
  ReactiveTemperatureInfo,
  ReactiveVibrationSensor,
  RpcCallOptions,
  SensorEventMessage,
  SensorRefreshedState,
  SensorRegistryRPC,
  StorageRPC,
  StoredSensorData,
  UseCameraByIdReturn,
  UseCameraStreamOptions,
  UseCuiFullscreenOptions,
  UseCuiFullscreenReturn,
  UseOAuthReturn,
  UsePluginReturn,
  UseRpcCallOptions,
  UseRpcCallReturn,
  UseRpcSubscriptionOptions,
  UseRpcSubscriptionReturn,
  UseSensorReturn,
  UseSensorsReturn,
  UseSensorsTypedReturn,
  UseSensorTypedReturn,
  UseSnapshotReturn,
  UseStorageReturn,
  UseTabVisibilityReturn,
  UseTerminalOptions,
  UseTerminalReturn,
} from './composables/index.js';

export { createActivityMode, STREAM_CONFIG } from './streaming/index.js';
export type {
  ActivityMode,
  ActivityModeConfig,
  CameraActivityMode,
  CodecCompatibility,
  ReactiveStream,
  StreamOptions,
  StreamStatus,
  VideoStreamingMode,
} from './streaming/index.js';

export type { BaseLogger, CameraUiContext, CameraUiEventCallback, CameraUiEventType, ReactiveCameraDevice, ReactiveCoreManager, ReactiveDeviceManager } from './types.js';

export type { Status as NatsStatus, RPCClient } from '@camera.ui/rpc';

export { NamespaceManager } from './server/index.js';
export type {
  CameraDeviceInterface,
  CameraNamespaces,
  CoreManagerInterface,
  CoreManagerNamespaces,
  DeviceManagerInterface,
  DeviceManagerNamespaces,
  FrameWorkerNamespaces,
  PluginCameraNamespaces,
  PluginNamespaces,
  PluginSensorNamespaces,
  SensorCameraViewNamespaces,
  SensorEventNamespaces,
  SensorProviderNamespaces,
  SensorRegistryNamespaces,
  TerminalManagerInterface,
  TerminalManagerNamespaces,
  TerminalOptions,
  TerminalSessionInfo,
} from './server/index.js';
